apiVersion: extensions.agents.x-k8s.io/v1alpha1
kind: SandboxWarmPool
metadata:
  name: alpha-transformer-pool
  namespace: default
spec:
  templateRef:
    name: alpha-transformer-sandbox
  replicas: 20
